import type { AgentMessage, LLMClient, LLMResponse, OpenAIToolDef } from "./types.js";

let seq = 0;
const nextId = (): string => `stubcall_${++seq}`;

/**
 * Deterministic stand-in for a real LLM. Replays a fixed tool-call plan —
 * web_search + db_query in parallel, then write_file, then a final
 * answer — so the whole agent loop is exercisable offline, in tests, and
 * in CI with zero secrets.
 */
export class StubLLM implements LLMClient {
  readonly name = "stub";

  complete(messages: AgentMessage[], tools: OpenAIToolDef[]): Promise<LLMResponse> {
    const toolRounds = messages.filter((m) => m.role === "tool").length;
    const has = (name: string): boolean => tools.some((t) => t.function.name === name);
    const userQuestion =
      [...messages].reverse().find((m) => m.role === "user" && "content" in m)?.content ??
      "the user's question";

    if (toolRounds === 0) {
      const calls = [];
      if (has("web_search")) {
        calls.push({
          id: nextId(),
          name: "web_search",
          arguments: JSON.stringify({ query: String(userQuestion).slice(0, 120), max_results: 3 }),
        });
      }
      if (has("db_query")) {
        calls.push({
          id: nextId(),
          name: "db_query",
          arguments: JSON.stringify({
            query: "SELECT id, title, topic, author, published_at FROM reports ORDER BY published_at DESC LIMIT 5",
          }),
        });
      }
      if (calls.length > 0) {
        return Promise.resolve({ content: null, toolCalls: calls });
      }
    }

    if (toolRounds > 0 && has("write_file") && !alreadyWrote(messages)) {
      return Promise.resolve({
        content: null,
        toolCalls: [
          {
            id: nextId(),
            name: "write_file",
            arguments: JSON.stringify({
              path: "reports/research-summary.md",
              content: buildStubReport(messages),
            }),
          },
        ],
      });
    }

    return Promise.resolve({
      content:
        "Stub answer: gathered evidence via MCP tools and persisted a report " +
        "to reports/research-summary.md inside the sandbox. (Run with " +
        "OPENAI_API_KEY set for a live model.)",
      toolCalls: [],
    });
  }
}

function alreadyWrote(messages: AgentMessage[]): boolean {
  return messages.some((m) => m.role === "tool" && m.name === "write_file");
}

function buildStubReport(messages: AgentMessage[]): string {
  const collected = messages
    .filter((m) => m.role === "tool")
    .map((m) => `## ${m.name}\n\n${m.content.slice(0, 800)}\n`)
    .join("\n");
  return [
    "# Research summary (stub run)",
    "",
    "Generated by the deterministic StubLLM — no OPENAI_API_KEY present.",
    "Each section below is raw output collected over the MCP protocol.",
    "",
    collected,
  ].join("\n");
}
